# Generated by Django 3.1.4 on 2020-12-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypswdsite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFOrm',
            new_name='Passwords',
        ),
    ]
